In [6]:
import numpy as np
import pandas as pd
import statsmodels.api as sm
import matplotlib.pyplot as plt
import seaborn as sns
import os
sns.set()

In [12]:
raw_data=pd.read_csv('2.01.+Admittance.csv')
print("Python is currently looking here:")
print(os.getcwd())
print("-" * 50)

Python is currently looking here:
C:\Users\Waheed\Desktop\AI stuff\stats-and-ai-learning
--------------------------------------------------

In [11]:
raw_data

      SAT Admitted
0    1363       No
1    1792      Yes
2    1954      Yes
3    1653       No
4    1593       No
..    ...      ...
163  1722      Yes
164  1750      Yes
165  1555       No
166  1524       No
167  1461       No

[168 rows x 2 columns]

In [13]:
data = raw_data.copy()
data['Admitted'] = data['Admitted'].map({'Yes':1,'No':0})

In [14]:
data

      SAT  Admitted
0    1363         0
1    1792         1
2    1954         1
3    1653         0
4    1593         0
..    ...       ...
163  1722         1
164  1750         1
165  1555         0
166  1524         0
167  1461         0

[168 rows x 2 columns]